# Generated by Django 2.0.2 on 2018-04-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='uploadFrequency',
        ),
    ]
