# Generated by Django 2.0.2 on 2018-04-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180424_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='uploadFrequency',
            field=models.IntegerField(default=0),
        ),
    ]
