# Generated by Django 2.0.2 on 2018-04-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20180424_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='memberinfo',
            name='uploadFrequency',
        ),
    ]
