# Generated by Django 2.0.2 on 2018-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180424_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
