# Generated by Django 2.0.2 on 2018-03-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='email',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
