# Generated by Django 2.0.2 on 2018-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20180419_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='selfDescription',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
