# Generated by Django 2.0.2 on 2018-03-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_invitationcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='email',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
