# Generated by Django 2.0.2 on 2018-03-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20180331_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='uploadFrequency',
            field=models.IntegerField(default=0),
        ),
    ]
